MAIL_CONFIG = '/etc/postfix'
SENDMAIL_CMD = '/sbin/sendmail'
LOGNAME = 'test'
DOMAIN = 'andrewyu.org'
RECIPIENT_DELIMITER = '+'
POSTMASTER = 'andrew@andrewyu.org'
SMTPHOST = 'localhost'
SMTPPORT = 0 # use smtplib default
PATH_TO_DBJSON = '/home/test/smlmp/db.json'
