LOGNAME = "smlmp"
DOMAIN = "andrewyu.org"
RECIPIENT_DELIMITER = "+"
POSTMASTER = "andrew@andrewyu.org"
SMTPHOST = "localhost"
SMTPPORT = 0  # use smtplib default
PATH_TO_DBJSON = "/srv/smlmp/smlmp/db.json"
HTTP_ROOT = "https://lists.andrewyu.org/"
ARCHIVER_ADDRESS = "public-inbox-user@andrewyu.org"
